# Generated by Django 3.2.3 on 2021-06-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=50, verbose_name='movie_name')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('category2', models.CharField(max_length=50, verbose_name='category2')),
                ('rate', models.PositiveIntegerField(verbose_name='rating')),
                ('rdate', models.DateField()),
                ('dur', models.TimeField()),
                ('poster', models.ImageField(upload_to='')),
                ('language', models.CharField(max_length=50, verbose_name='language')),
            ],
        ),
    ]
