# Generated by Django 3.2.3 on 2021-06-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(upload_to='admin/movies_images/'),
        ),
    ]
