# Generated by Django 3.2.3 on 2021-06-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_book', '0002_alter_movies_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='city'),
        ),
    ]
