# Generated by Django 3.2.3 on 2021-06-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_book', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='User_Name')),
                ('Email', models.EmailField(max_length=254, verbose_name='User_Email')),
                ('city', models.CharField(default='', max_length=50, verbose_name='User_city')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('contact', models.PositiveIntegerField(verbose_name='contact')),
            ],
        ),
    ]
