# Generated by Django 3.2.3 on 2021-06-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_book', '0005_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Theatre_Name')),
                ('Email', models.EmailField(max_length=254, verbose_name='Theatre_Email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('contact', models.PositiveIntegerField(verbose_name='contact')),
                ('screen', models.PositiveIntegerField(verbose_name='Screen_No')),
                ('city', models.CharField(max_length=50, verbose_name='Theatre_city')),
            ],
        ),
    ]
