# Generated by Django 3.2.3 on 2021-06-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_book', '0006_theatre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatre',
            old_name='screen',
            new_name='total_screen',
        ),
        migrations.CreateModel(
            name='Show_available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('screen', models.PositiveIntegerField(verbose_name='Screen')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_book.theatre')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_book.movies')),
            ],
        ),
    ]
