# Generated by Django 3.2.3 on 2021-06-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_book', '0008_rename_mid_show_available_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=50, verbose_name='seat')),
                ('ticket', models.PositiveIntegerField(verbose_name='No Ticket')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_book.show_available')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_book.users')),
            ],
        ),
    ]
